name: Sync from upstream
on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/marioaldayuz/free-highlevel-support-kb.git || true
          git fetch upstream

      - name: Merge upstream/main into main (keeps your workflow)
        run: |
          git checkout main
          git merge --no-edit upstream/main || true

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
